export interface Contact {
    cid: string,
    name: string,
    email: string,
    phone: string,
    contactMethod: string,
    language: string,
    gender: string,
    race: string,
    business: string,
    website: string,
    businessStatus: string,
    address: string,
    immigrant: boolean,
    nonNativeEnglish: boolean,
    lowIncome: boolean,
    wasUnemployed: boolean,
    veteran: boolean,
}